### PR TITLE
add errors for constraints on types

### PR DESCRIPTION
**Pull request by mvnetbiz**
I wanted to be able to get errors from constraints on a domain. This worked for me.
Is adding the 2nd function the best way, and is it okay to change the exported function name?

### CODE REVIEW

**Review by enisdenjo — COMMENTED** [review]
This looks great, thank you!

I'd recommend updating the [example in the readme](https://www.typescriptlang.org/play?ts=5.0.4#code/JYOwLgpgTgZghgYwgAgMoAs4AcUG8BQyycUEcAFAB4BcyIArgLYBG0AlLQy9ANyHGkKNOk1ZQANMgCenUe1oBnMFFABzPkRJkqs7hOkB+XWI4i9yAD7IlKkOvwBffAgA2cBQrSYcASUZYXZGB-FwhGCHBPDGw8fi0KAH1hLjFJBKkjMxNjaEtrZTVkAiIiUjB6KBBkAAYNZCcnBAB7ECUzHKhkAF5kchAIAHcvGL8A8jY2ADp48gBmNj5m1rB8qEUCu27e-qHo3xDxqZnZyXmeIA) to reflect that type constraints can be manipulated too.

**Review by enisdenjo — APPROVED** [review]

**Comment by mvnetbiz** [comment]
I added an example. In my case I am using crypt() on the password and only storing the hash, but I am just using the domain as a place to "store" the checks so I can test them like `new_pass::strong_password` in multiple functions.

**Review by enisdenjo — APPROVED** [review]
Looks great! 🚀

**Comment by enisdenjo** [comment]
Released in [v1.1.0](https://www.npmjs.com/package/@graphile-contrib/constraint-error-tags/v/1.1.0).

**Pull request merged**
